"""Add color to UserActivity

Revision ID: 19a9b4e3b89b
Revises: 2c1859e56cf0
Create Date: 2025-05-03 14:32:01.586090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a9b4e3b89b'
down_revision = '2c1859e56cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
