"""Add position column to assessments

Revision ID: 20f1c06bc5fe
Revises: fe7a34408db8
Create Date: 2025-05-10 01:39:00.496721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f1c06bc5fe'
down_revision = 'fe7a34408db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
