"""Add timetable_request table

Revision ID: d482523deb80
Revises: 4fb2e93a1505
Create Date: 2025-05-04 10:38:10.473386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd482523deb80'
down_revision = '4fb2e93a1505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user_details.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notifications')
    op.drop_table('timetable_shares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_shares',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('shared_with_id', sa.INTEGER(), nullable=False),
    sa.Column('is_accepted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user_details.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user_details.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('timetable_request')
    # ### end Alembic commands ###
