"""Add full_availability to ActivityTimeSlot

Revision ID: e9c6be3f4112
Revises: d482523deb80
Create Date: 2025-05-05 12:01:42.237027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c6be3f4112'
down_revision = 'd482523deb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_time_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_availability', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_time_slot', schema=None) as batch_op:
        batch_op.drop_column('full_availability')

    # ### end Alembic commands ###
