"""Add activity_type column

Revision ID: fe7a34408db8
Revises: e9c6be3f4112
Create Date: 2025-05-09 16:17:33.046854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7a34408db8'
down_revision = 'e9c6be3f4112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('score_obtained', sa.Float(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_time_slot', schema=None) as batch_op:
        batch_op.drop_column('full_availability')

    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_column('activity_type')

    with op.batch_alter_table('activity_time_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_availability', sa.BOOLEAN(), nullable=True))

    op.drop_table('assessments')
    # ### end Alembic commands ###
